### ISSUE TITLE
Vulnerable algorithm

### ISSUE THREAD

**Issue by aleksradojkovic** [DevMomo/Diffie-Hellman-Arduino#1]
Dear,

This project is vulnerable to brute-force attacks, due to low key size. 

uint32_t key is not sufficient size, to call this algorithm secure. It should be a key of, at least 1024 bits. (Altought it is considered as insecure, too).

However, this project is fine, works good. If I have a time, I'll modify this project, in first place, the size of key.

Thank you

**Comment by DevMomo** [comment]
I've added a comment to serve as a warning. I'll leave it unchanged as this is a simple working model. Thanks for the heads up! :)
